#              _                        _   _
#   __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __
#  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
# | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
#

- alias: Notify on Hass Startup
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.pushbullet
    data:
      message: Home Assistant has been initialized.
      title: Hass Startup
- alias: Notify on Hass Shutdown
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: notify.pushbullet
    data:
      message: Home Assistant is processing a shutdown or restart.
      title: Hass Shutdown
- alias: Sunrise
  trigger:
    platform: time
    after: "07:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.upstairs_sunrise
- alias: Notify on Print Complete
  trigger:
    platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
  action:
    service: notify.pushbullet
    data:
      message: Octoprint has stopped printing.
      title: Octoprint
