#              _                        _   _
#   __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __
#  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
# | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
#

# HOME ASSISTANT STATUS
- alias: Notify on Hass Startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: notify.pushbullet
    data:
      message: Home Assistant has been initialized.
      title: Hass Startup

- alias: Notify on Hass Shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  action:
  - service: notify.pushbullet
    data:
      message: Home Assistant is processing a shutdown or restart.
      title: Hass Shutdown

# SCENE AUTOMATION
- alias: Sunrise
  trigger:
  - platform: time
    at: "07:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: script.upstairs_sunrise

- alias: Downstairs Sunlight
  trigger:
    - platform: time
      at: "17:00:00"
    - platform: time
      at: "19:00:00"
    - platform: time
      at: "21:00:00"
  condition:
    # Test two lights, in case one is offline
    condition: or
    conditions:
      - condition: state
        entity_id: 'light.workstation'
        state: 'on'
      - condition: state
        entity_id: 'light.kitchen'
        state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          scene.downstairs_{% if now().hour <= 17 %}afternoon{% elif now().hour >= 21 %}night{% else %}evening{% endif %}
    - service: notify.notify
      data_template:
        message: >
          Switching to scene.downstairs_{% if now().hour <= 17 %}afternoon{% elif now().hour >= 21 %}night{% else %}evening{% endif %}

# OCTOPRINT
- alias: Notify on Print Complete
  trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
  action:
  - service: notify.pushbullet
    data:
      message: Octoprint has stopped printing.
      title: Octoprint
