#              _                        _   _
#   __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __
#  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
# | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
#  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
#

# HOME ASSISTANT STATUS
- alias: Notify on Hass Startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: notify.pushbullet
    data:
      message: Home Assistant has been initialized.
      title: Hass Startup

- alias: Notify on Hass Shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  action:
  - service: notify.pushbullet
    data:
      message: Home Assistant is processing a shutdown or restart.
      title: Hass Shutdown

# SCENE AUTOMATION
- alias: Sunrise
  trigger:
  - platform: time
    at: "07:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: script.upstairs_sunrise

- alias: Downstairs Sunlight
  trigger:
    - platform: time_pattern
      minutes: 1
  condition:
    # Test two lights, in case one is offline
    condition: or
    conditions:
      - condition: state
        entity_id: 'light.workstation'
        state: 'on'
      - condition: state
        entity_id: 'light.kitchen'
        state: 'on'
  action:
    - service: script.downstairs_lights_on

# OCTOPRINT
- alias: Notify on Print Complete
  trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
  action:
  - service: notify.pushbullet
    data:
      message: Octoprint has stopped printing.
      title: Octoprint

# REMOTES
- alias: Remote button for Returning Home
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
      scene_id: 4
      scene_data: 7680
  action:
  - service: script.downstairs_lights_on
- alias: Remote button for Daylight Downstairs
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
      scene_id: 1
      scene_data: 7680
  action:
  - service: scene.turn_on
    entity_id: scene.daylight_downstairs
- alias: Remote button for Leave
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
      scene_id: 3
      scene_data: 7680
  action:
  - service: scene.turn_on
    entity_id: scene.leave
- alias: Remote button for Goodnight
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
      scene_id: 2
      scene_data: 7680
  action:
  - service: homeassistant.turn_off
    entity_id: group.lights_downstairs
  - service: scene.turn_on
    entity_id: scene.night_upstairs
