homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.301507
  longitude: -97.698620
  # C for Celsius, F for Fahrenheit
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  ssl_certificate: /home/hass/.homeassistant/cert.pem
  ssl_key: /home/hass/.homeassistant/key.pem

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

# Checks for available updates
updater:

# Track the sun
sun:

# Discover some devices automatically
discovery:

zone:
  name: Home
  latitude: 30.301507
  longitude: -97.698620
  radius: 250
  icon: mdi:home-variant

sensor: !include sensor.yaml

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

camera:
  - platform: mjpeg
    name: Printer Camera
    mjpeg_url: http://192.168.1.49/webcam/?action=stream
    still_image_url: http://192.168.1.49/webcam/?action=snapshot

light:
  - platform: lifx

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/src/open-zwave-control-panel/config
  polling_interval: 120000

ifttt:
  key: !secret ifttt_api

octoprint:
  host: 192.168.1.49
  api_key: !secret octoprint_api

weblink:
  entities:
    - name: OctoPi Home
      url: https://192.168.1.49

group: !include group.yaml

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api
    name: pushbullet

automation: !include automation.yaml

script: !include script.yaml

scene: !include scene.yaml

alexa: !include alexa.yaml
