#  _
# | |__   __ _ ___ ___
# | '_ \ / _` / __/ __|
# | | | | (_| \__ \__ \
# |_| |_|\__,_|___/___/
#
# Home Assistant (https://home-assistant.io) configuration for
# tsmith512's otherwise rather disorganized apartment.

### BASICS:

homeassistant:
  name: Home
  latitude: 30.301507
  longitude: -97.698620
  elevation: 188
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml


### STANDARD COMPONENTS WITHOUT CONFIGURATION:

# Enable frontend
frontend:

# Record events
logbook:

# Enable the Config UI
config:

# Voice commends in frontend
conversation:

# Check for updates
updater:
  include_used_components: true

# Track sunrise/sunset
sun:

# Auto discovery service
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

### STARTER COMPONENTS

http:
  api_password: !secret http_password
  ssl_certificate: /home/hass/.homeassistant/cert.pem
  ssl_key: /home/hass/.homeassistant/key.pem

# @TODO: There's no presence detection here; unnecessary?
zone:
  name: Home
  latitude: 30.301507
  longitude: -97.698620
  radius: 250
  icon: mdi:home-variant


### SENSORS, DEVICES, AND SERVICE INTEGRATIONS

sensor: !include sensor.yaml

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

camera:
  - platform: mjpeg
    name: Printer Camera
    mjpeg_url: http://192.168.1.49/webcam/?action=stream
    still_image_url: http://192.168.1.49/webcam/?action=snapshot

light:
  - platform: lifx

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/src/open-zwave-control-panel/config
  polling_interval: 120000

ifttt:
  key: !secret ifttt_api

octoprint:
  host: 192.168.1.49
  api_key: !secret octoprint_api

weblink:
  entities:
    - name: OctoPi Home
      url: https://192.168.1.49


notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api
    name: pushbullet


### EXTERNAL CONFIGURATION SECTIONS

group: !include group.yaml

automation: !include automation.yaml

script: !include script.yaml

scene: !include scene.yaml

alexa: !include alexa.yaml
