#  _
# | |__   __ _ ___ ___
# | '_ \ / _` / __/ __|
# | | | | (_| \__ \__ \
# |_| |_|\__,_|___/___/
#
# Home Assistant (https://home-assistant.io) configuration for
# tsmith512's otherwise rather disorganized apartment.

### BASICS:

homeassistant:
  name: Home
  latitude: !secret loc_latitude
  longitude: !secret loc_longitude
  elevation: 188
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_domain:
    sensor:
      haaska_hidden: true
    binary_sensor:
      haaska_hidden: true
  customize_glob:
    "sensor.dark_sky*":
      haaska_hidden: true
    "group.all_*":
      haaska_hidden: true
    "group.*_scenes":
      haaska_hidden: true
    "group.weather*":
      haaska_hidden: true
    "group.printer*":
      haaska_hidden: true

### STANDARD COMPONENTS WITHOUT CONFIGURATION:

# Enable frontend
frontend:

# Record events
logbook:

# Enable the Config UI
config:

# Voice commends in frontend
conversation:

# Check for updates
updater:
  include_used_components: true

# Track sunrise/sunset
sun:

# Auto discovery service
discovery:

# Enables support for tracking state changes over time
history:

# Text to speech
tts:
  - platform: google

### STARTER COMPONENTS

http:
  api_password: !secret http_password
  ssl_certificate: /home/homeassistant/.homeassistant/cert.pem
  ssl_key: /home/homeassistant/.homeassistant/key.pem

# @TODO: There's no presence detection here; unnecessary?
zone:
  name: Home
  latitude: !secret loc_latitude
  longitude: !secret loc_longitude
  radius: 250
  icon: mdi:home-variant


### SENSORS, DEVICES, AND SERVICE INTEGRATIONS

sensor: !include sensor.yaml

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

camera:
  - platform: mjpeg
    name: Printer Camera
    mjpeg_url: http://10.0.1.11/webcam/?action=stream
    still_image_url: http://10.0.1.11/webcam/?action=snapshot

light:
  - platform: lifx
    server: !secret iot_wifi_server
    broadcast: !secret iot_wifi_broadcast

climate:
  - platform: zwave

zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: false

ifttt:
  key: !secret ifttt_api

octoprint:
  host: 10.0.1.11
  api_key: !secret octoprint_api

weblink:
  entities:
    - name: OctoPi Home
      url: https://10.0.1.11


notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api
    name: pushbullet


### EXTERNAL CONFIGURATION SECTIONS

group: !include group.yaml

automation: !include automation.yaml

script: !include script.yaml

scene: !include scene.yaml

alexa: !include alexa.yaml
