#  ___  ___ _ __  ___  ___  _ __
# / __|/ _ \ '_ \/ __|/ _ \| '__|
# \__ \  __/ | | \__ \ (_) | |
# |___/\___|_| |_|___/\___/|_|
#
# Standard sensors, though I'm not sure a separate file was really
# useful for this.

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - daily_summary
    - hourly_summary
    - temperature
    - temperature_min
    - temperature_max
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - precip_type
    - precip_intensity
    - precip_probability
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
    - Temperatures
    - Job Percentage
